project:
  type: website
  output-dir: docs

website:
  title: "KU Med English III, IV"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Past"
        menu:
          - text: "2025 Autumn"
            href: 2025_Autumn.qmd


format:
  html:
    theme:
      - minty
      - custom.scss
    toc: true



