---
title: "医学英語 III, IV"
---

こちらは、杏林大学医学部医学科 医学英語 III, IV (馬場班) のサイトです。

## 医学英語 III

2026年 春学期

| 回  | 日 | 教室  | ファイル | 内容 |
|--|--|--|--|--|
| 1 | 4/2 | 604 | [レジュメ (研究デザイン)](https://babayoshihiko.github.io/How/design.html) | ガイダンス | 
| 2 | 4/9 | 604 | [レジュメ (フレイル)](https://babayoshihiko.github.io/How/frailty.html) | 論文1: Fried LP et al. (2001) Frailty in Older Adults: Evidence for a Phenotype, *J Gerontol Med Sci*, **56**(3), M146-M157. |
|  | 4/16 | - | | 実習のため英語なし |
| 3 | 4/23 | 604 | [レジュメ (メタ分析)](https://babayoshihiko.github.io/How/meta_intro.html)<br />[レジュメ (論文)](https://kyorin.pages.dev/meta_vetrano.html) | 論文2: Vetrano DL, Palmer KM, Galluzzo L, Giampaoli S, Marengoni A, Bernabei R, & Onder G (2018). Hypertension and frailty: a systematic review and meta-analysis. *BMJ open*, **8**(12), e024406. |
|  | 4/30 | - | | 4/30 は休 |
| 4 | 5/7 | 604 |  | 論文3: 教科書 文例5 |
| 5 | 5/14 | 202 | [参考問題](https://kyorin.pages.dev/meta_vetrano_q.html) | 小テスト: 論文2 を印刷して渡します。この論文についてしてください。本番は Microsoft Forms です。参考問題は簡易版です。 |
| 6 | 5/21 | 	604	| [レジュメ](https://babayoshihiko.github.io/How/rct_intro.html)<br />[レジュメ](https://kyorin.pages.dev/rct_teh.html) | 論文4: Teh R, Barnett D, Edlin R et al. (2022). Effectiveness of a complex intervention of group-based nutrition and physical activity to prevent frailty in pre-frail older adults (SUPER): A randomised controlled trial. The Lancet Healthy Longevity, 3(8), e519-e530. | 
| 7 | 	5/28 | 604 | | つづき | 
| 8 | 	6/4 | 604	| 未定 | 	未定 | 
| 9 | 	6/11 | 202 | [参考問題](https://docs.google.com/forms/d/e/1FAIpQLSeEI0pFkn-cZTdrIPrbXhW5z1Pq6cPuHLH8r0yxcHSd3hLn8A/viewform?usp=header) | 	小テスト: 論文4 を基にした課題 | 
| 10 | 	6/18 | 604	| [レジュメ](https://babayoshihiko.github.io/How/crosssectional_intro.html)<br />[レジュメ](http://kyorin.pages.dev/crosssectional_liu.html) |	論文5: Liu W, Puts M, Jian F, Zhou C, Tang S and Chen S (2020) Physical frailty and its associated factors among elderly nursing home residents in China |
| 11 | 	6/25 |	604 | Active Learning 1 | つづき |
| 12 | 	7/2 |	604	|  Active Learning 2 	| つづき |
| 期末	| -- | -- | -- | 期末テスト: Liu W et al (2020) BMC Geriatr より出題 |

: 2026年 春学期 日程 {tbl-colwidths="[1,1,3,35,60]"}


## 医学英語 IV

2026年 春学期

医学英語 IV (馬場班) では、以下の論文を読みます。

Wang ZT, Yan F, Zhang YR *et al.* (2022). Modified dementia risk score as a tool for the prediction of dementia: a prospective cohort study of 239745 participants. *Translational Psychiatry*, 12(1), 509.

この論文は、

- ロジスティック回帰: オッズ比とベータ
- 生存分析: Kaplan-Meier, ハザード比
- スクリーニングツール (作成と評価): Receiver-Operator Characteristics (ROC), Area Under the Curve (AUC)

から構成されています。

つまり、1 つの論文で、3 つの研究デザインを学ぶことができます。

| 回  | B1 | E1 | 教室  | ファイル | 内容 |
|--|--|--|--|--|--|
| 1 | 4/2 | 5/21 | 604 |  | ガイダンス | 
| 2 | 4/9 | 5/28 | 604 | [レジュメ (横断研究)](https://babayoshihiko.github.io/How/crosssectional_intro.html)<br />[レジュメ (論文)](https://kyorin.pages.dev/screening_wang.html) | ロジスティック回帰  |
| 3 | 4/16 | 6/4 | 604 | [レジュメ (コホート研究)](https://kyorin.pages.dev/cohort_intro.html)<br />[レジュメ (論文)](https://kyorin.pages.dev/screening_wang.html) | 生存分析 |
| 4 | 4/23 | 6/11 | 604 | [レジュメ (スクリーニング)](https://babayoshihiko.github.io/How/screening_intro.html)<br />[レジュメ (論文)](https://kyorin.pages.dev/screening_wang.html) | スクリーニングツール |
|   | 4/30 | --- | --- |  | 4/30 は休 |
| 5 | 5/7 | 6/18 | 202 | [参考問題](https://kyorin.pages.dev/screening_wang_q.html) | 小テスト: 論文 を印刷して渡します。この論文についてしてください。本番は Microsoft Forms です。参考問題は簡易版です。  |
| 6 | 5/14 | 6/25 | 604 |  | Active Learning |


: 2026年 春学期 日程 {tbl-colwidths="[1,1,1,3,33,60]"}
